# List all Portfolio
GET https://portfolio-be-257238999717.us-central1.run.app/portfolio

###### List all Portfolio
GET http://localhost:8080/auth/

###### List all Portfolio
GET http://localhost:8080/

#### Authentication
POST http://localhost:8080/auth/login
Content-Type: application/json 

{
  "username": "huyenvo",
  "password": "huyenvo"
}

#### Authentication
POST https://portfolio-be-257238999717.us-central1.run.app/auth/login
Content-Type: application/json 

{
  "username": "huyenvo",
  "password": "huyenvo"
}

#### Create Port
POST http://localhost:3000/create-portfolio
content-Type: application/json

{
  "title": "Donald J Trump",
  "background": "Testinggg",
  "uploadFile": "asdf",
  "strategy": "Createtive Idea",
  "execution": "Ronaldo",
  "creative": "Gump",
  "people": [
    {
      "name": "Huyen Vo",
      "company": "Circus",
      "role": "Planner"
    },
    {
      "name": "Roberto Concha Rodríguez",
      "company": "GUT Mexico City",
      "role": "Sr. Copywriter"
    },
    {
      "name": "Alejandra Margain",
      "company": "GUT Mexico City",
      "role": "Strategy Director"
    }
  ]
}


