# List all Portfolio
GET http://localhost:3000/portfolio
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imh1eWVudm8iLCJpYXQiOjE3MzM3NDA0NzAsImV4cCI6MTczMzc0MDk3MH0.EYfKs8FJGbPKS5Nc15TSWBP5LMvzONMRykRCvJGGqr8

#### Auth
GET  http://localhost:3000/auth/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imh1eWVudm8iLCJpYXQiOjE3MzM3NDA0NzAsImV4cCI6MTczMzc0MDk3MH0.EYfKs8FJGbPKS5Nc15TSWBP5LMvzONMRykRCvJGGqr8

#### Authentication
POST http://localhost:3000/auth/login
Content-Type: application/json 

{
  "username": "huyenvo",
  "password": "huyenvo"
}

#### Create Port
POST http://localhost:3000/portfolio/create-portfolio
content-Type: application/json

{
  "title": "Donald J Trump",
  "background": "Testinggg",
  "strategy": "Createtive Idea",
  "execution": "Ronaldo",
  "creative": "Gump",
  "people": [
    {
      "name": "Huyen Vo",
      "company": "Circus",
      "role": "Planner"
    },
    {
      "name": "Roberto Concha Rodríguez",
      "company": "GUT Mexico City",
      "role": "Sr. Copywriter"
    },
    {
      "name": "Alejandra Margain",
      "company": "GUT Mexico City",
      "role": "Strategy Director"
    }
  ]
}

#### Delete Port
DELETE http://localhost:3000/portfolio/2

#### USER
POST http://localhost:3000/user/signup
Content-Type: application/json

{
  "email": "onlyFan@anything.com",
  "password": "33333"
}

#### UPDATE
PATCH http://localhost:3000/portfolio/106
content-Type: application/json

{
  "title": "Donald J Trump",
  "background": "Testinggg",
  "strategy": "Createtive Idea",
  "execution": "Ronaldo",
  "creative": "Gump",
  "people": [
    {
      "name": "Huyen Vo",
      "company": "Circus",
      "role": "Planner"
    },
    {
      "name": "Roberto Concha Rodríguez",
      "company": "GUT Mexico City",
      "role": "Sr. Copywriter"
    },
    {
      "name": "Alejandra Margain",
      "company": "GUT Mexico City",
      "role": "Strategy Director"
    }
  ]
}

#### REMOVE USER
DELETE http://localhost:3000/user/5

